// Sample reconciler prompts — mirrors SAMPLE_RECONCILER_PROMPTS in /model-comparison.
// Used by the Reconcilier-mode reconciler card in MAS Panel.

export const SAMPLE_RECONCILER_PROMPTS: Record<string, string> = {
  "Majority vote": `Pick the answer that the majority of workers agree on. If there is a tie, pick the answer from the highest-ranked worker.\n\nRULES:\n- Output the majority answer directly\n- If tied, prefer Worker 1's answer\n- No explanations, no reasoning, no commentary`,
  "Best quality pick": `Evaluate each worker's output for accuracy, completeness, and clarity. Pick the single best response.\n\nRULES:\n- Output the best answer directly\n- No explanations, no reasoning, no commentary`,
  "Synthesize all": `Combine the best parts of all worker outputs into one comprehensive answer.\n\nRULES:\n- Merge insights from all workers into a single coherent response\n- Do not simply copy one worker — synthesize\n- No explanations, no reasoning, no commentary`,
  "Conservative merge": `Compare all worker responses and identify only the claims, codes, or findings that appear in at least two independent responses. Discard claims made by only one worker.\n\nRULES:\n- Extract discrete claims from each response\n- Only retain claims corroborated by 2+ workers\n- Synthesize retained claims into a coherent response\n- Prefer precision over recall\n- No explanations, no reasoning, no commentary`,
  "Devil's advocate": `For each worker response, identify the strongest possible counterargument or most critical flaw. Then select the response that best withstands this scrutiny.\n\nRULES:\n- Eliminate responses with factual errors or logical fallacies\n- Select the response with the least damaging weakness\n- If all responses have critical flaws, synthesize a corrected answer\n- Output the final answer directly\n- No explanations, no reasoning, no commentary`,
  "Iterative refinement": `Treat Worker 1's response as the initial draft. For each subsequent worker response, identify improvements — corrections, additions, or better phrasing — and apply them incrementally to build the best possible answer.\n\nRULES:\n- Start with Worker 1 as baseline\n- For each additional worker, only adopt changes that clearly improve accuracy or completeness\n- Do not degrade existing correct content\n- Output the final refined response\n- No explanations, no reasoning, no commentary`,
};
